stages:
  - test
  - build

test:
  stage: test
  image: python:3.6-slim
  before_script:
    - pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
    - pip3 install -e .
    - python3 -m pip install types-requests
    - python3 -m pip install types-PyYAML
    - pip3 install black
    - pip3 install mypy
  script:
    - black . --check --diff
    - mypy .

buildkitd:
  stage: build
  tags:
  - docker
  script:
  - mkdir -p ~/.docker
  - echo "{\"auths\":{\"https://${CI_REGISTRY}\":{\"username\":\"${CI_REGISTRY_USER}\",\"password\":\"${CI_REGISTRY_PASSWORD}\"}}}" > ~/.docker/config.json
  - docker build ./ -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHORT_SHA}
  - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHORT_SHA}
  - docker rmi ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHORT_SHA}

  dependencies:
    - test
