stages:
  - test
  - build

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

test:
  stage: test
  image: python:3.6-slim
  before_script:
    - pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
    - pip3 install -e .
    - python3 -m pip install types-requests
    - python3 -m pip install types-PyYAML
    - pip3 install black
    - pip3 install mypy
  script:
    - black . --check --diff
    - mypy .

buildkitd:
  stage: build
  services:
  - alias: buildkitd
    name: moby/buildkit:rootless
    command:
    - "--oci-worker-no-process-sandbox"
    - "--addr"
    - "tcp://0.0.0.0:1234"
  variables:
    BUILDKIT_HOST: tcp://buildkitd:1234
  image:
    name: moby/buildkit:rootless
    entrypoint: [ "sh", "-c" ]
  script:
  - mkdir -p ~/.docker
  - echo "{\"auths\":{\"https://${CI_REGISTRY}\":{\"username\":\"${CI_REGISTRY_USER}\",\"password\":\"${CI_REGISTRY_PASSWORD}\"}}}" > ~/.docker/config.json
  - |
    buildctl build \
        --frontend=dockerfile.v0 \
        --local context=. \
        --local dockerfile=dockerfiles \
        --opt build-arg:ID_RSA=${GITLAB_ID_RSA} \
        --export-cache mode=max,type=registry,ref=${CI_REGISTRY_IMAGE}/buildcache:${CI_COMMIT_REF_SLUG},push=true \
        --import-cache type=registry,ref=${CI_REGISTRY_IMAGE}/buildcache:${CI_COMMIT_REF_SLUG} \
        --output type=image,name=${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHORT_SHA},push=true

  dependencies:
    - test