stages:
  - test
  - build
test:
  stage: test
  image: python:3.6-slim
  before_script:
    - pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
    - python3 -m pip install types-requests
    - python3 -m pip install types-PyYAML
    - pip3 install black
    - pip3 install mypy
  script:
    - black . --check --diff
    - mypy .
buildkitd:
  stage: build
  tags:
  - docker
  script:
  - mkdir -p ~/.docker
  - echo "{\"auths\":{\"https://${TENCENTREGISTRY}\":{\"username\":\"${TENCENT_REGISTRY_USER}\",\"password\":\"${TENCENT_REGISTRY_PASSWORD}\"}}}" > ~/.docker/config.json
  - docker build ./ -t ${TENCENTREGISTRY}/${CI_PROJECT_NAME}/${CI_COMMIT_REF_SLUG}:${CI_COMMIT_SHORT_SHA}
  - docker push ${TENCENTREGISTRY}/${CI_PROJECT_NAME}/${CI_COMMIT_REF_SLUG}:${CI_COMMIT_SHORT_SHA}
  - docker rmi ${TENCENTREGISTRY}/${CI_PROJECT_NAME}/${CI_COMMIT_REF_SLUG}:${CI_COMMIT_SHORT_SHA}

  dependencies:
    - test
deploy_developenv:
  image:
    harbor.nolibox.com/base-image/buildyaml:latest
  stage: deploytest
  script:
    - mkdir -p ~/.kube/
    - echo $gpu_kube_config | base64 -d > ~/.kube/config
    - kubectl set image deployment ${CI_PROJECT_NAME} ${CI_PROJECT_NAME}=${TENCENTREGISTRY}/${CI_PROJECT_NAME}/${CI_COMMIT_REF_SLUG}:${CI_COMMIT_SHORT_SHA} -n test --record
  except:
    refs:
      - master
      - main
