backend: "python"
max_batch_size: 4
instance_group [{ kind: KIND_CPU }]

input [
{
    name: "input"
    data_type: TYPE_UINT8
    dims: [ 320, 320, 3 ]
}
]

output [
{
    name: "predictions"
    data_type: TYPE_FP32
    dims: [ 320, 320 ]
}
]